{
  "x-generator": "NSwag v13.9.4.0 (NJsonSchema v10.3.1.0 (Newtonsoft.Json v9.0.0.0))",
  "openapi": "3.0.0",
  "info": {
    "title": "National Registry",
    "description": "The API retrieves information about individuals stored in the Icelandic registry.",
    "contact": {
      "name": "Skra.is",
      "url": "https://www.skra.is/",
      "email": "skra@skra.is"
    },
    "version": "0.1.0",
    "x-category": [
      "personal",
      "official"
    ],
    "x-pricing": [
      "paid"
    ]
  },
  "servers": [
  ],
  "paths": {
    "/api/v1/einstaklingar/{id}": {
      "get": {
        "tags": [
          "Einstaklingar"
        ],
        "summary": "Get the basic information for an individual.",
        "operationId": "Einstaklingar_GetEinstaklingur",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "National id of the individual being fetched.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "The basic information for the individual.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Einstaklingsupplysingar"
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "404": {
            "description": "No individual exists with that national id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/einstaklingar/{id}/faedingarstadur": {
      "get": {
        "tags": [
          "Einstaklingar"
        ],
        "summary": "Get the registered birthplace for an individual.",
        "operationId": "Einstaklingar_GetFaedingarstadur",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "National id of the individual.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "The birthplace information for the individual.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Faedingarstadur"
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "404": {
            "description": "No individual exists with that national id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/einstaklingar/{id}/rikisfang": {
      "get": {
        "tags": [
          "Einstaklingar"
        ],
        "summary": "Get the citizenship for an individual.",
        "operationId": "Einstaklingar_GetRikisfang",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "National id of the individual.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "The citizenship information for the individual.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Rikisfang"
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "404": {
            "description": "No individual exists with that national id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/einstaklingar/{id}/trufelag": {
      "get": {
        "tags": [
          "Einstaklingar"
        ],
        "summary": "Get the religion registration for an individual.",
        "operationId": "Einstaklingar_GetTrufelag",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "National id of the individual.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "The religion registration information for the individual.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Trufelagsskraning"
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "404": {
            "description": "No individual exists with that national id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/einstaklingar/{id}/logheimili": {
      "get": {
        "tags": [
          "Einstaklingar"
        ],
        "summary": "Get the legal domicile for an individual.",
        "operationId": "Einstaklingar_GetLogheimili",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "National id of the individual.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "The legal domicile registered for the individual.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Heimili"
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "404": {
            "description": "No individual exists with that national id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/einstaklingar/{id}/adsetur": {
      "get": {
        "tags": [
          "Einstaklingar"
        ],
        "summary": "Get the residence information for an individual.",
        "operationId": "Einstaklingar_GetAdsetur",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "National id of the individual.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "The residence information registered for the individual.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Adsetur"
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "404": {
            "description": "No individual exists with that national id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/einstaklingar/{id}/buseta": {
      "get": {
        "tags": [
          "Einstaklingar"
        ],
        "summary": "Get the residence history for an individual.",
        "operationId": "Einstaklingar_GetBuseta",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "National id of the individual.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "The residence history registered for the individual.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Heimili"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "404": {
            "description": "No individual exists with that national id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/einstaklingar/{id}/lograda": {
      "get": {
        "tags": [
          "Einstaklingar"
        ],
        "summary": "Is the individual of legal age.",
        "operationId": "Einstaklingar_GetLograda",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "National id of the individual.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "Yes or no answer depending on if the individual is of legal age.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Lograda"
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "404": {
            "description": "No individual exists with that national id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/einstaklingar/{id}/hjuskapur": {
      "get": {
        "tags": [
          "Einstaklingar"
        ],
        "summary": "Get the cohabitation information for an individual.",
        "operationId": "Einstaklingar_GetHjuskapur",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "National id of the individual.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "The registered cohabitation details for the individual.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Hjuskapur"
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "404": {
            "description": "No individual exists with that national id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/einstaklingar/{id}/fjolskyldumedlimir": {
      "get": {
        "tags": [
          "Einstaklingar"
        ],
        "summary": "Get a list of family members for an individual.",
        "operationId": "Einstaklingar_GetFjolskyldumedlimir",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "National id of the individual.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "List of family members for the individual.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fjolskylda"
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "404": {
            "description": "No individual exists with that national id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/einstaklingar/{id}/logborn": {
      "get": {
        "tags": [
          "Einstaklingar"
        ],
        "summary": "Get all the children the individual is a legal parent of.",
        "operationId": "Einstaklingar_GetLogborn",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "National id of the individual.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "List of all the children the individual is a legal parent of.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "404": {
            "description": "No individual exists with that national id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/einstaklingar/{id}/logforeldrar": {
      "get": {
        "tags": [
          "Einstaklingar"
        ],
        "summary": "Get the legal parents of an individual.",
        "operationId": "Einstaklingar_GetLogforeldrar",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "National id of the individual.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "A list of the individuals legal parents.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "404": {
            "description": "No individual exists with that national id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/einstaklingar/{id}/forsja": {
      "get": {
        "tags": [
          "Einstaklingar"
        ],
        "summary": "Get the list of childrens the individual has custody of.",
        "operationId": "Einstaklingar_GetForsja",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "National id of the individual.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "List of all the children the individual has custody of.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "404": {
            "description": "No individual exists with that national id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side."
          }
        }
      }
    },
    "/api/v1/einstaklingar/{id}/forsja/{barn}": {
      "get": {
        "tags": [
          "Einstaklingar"
        ],
        "summary": "Get the parents that have custody of the child.",
        "operationId": "Einstaklingar_GetForsjaForeldri",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "Kennitala einstaklings.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          },
          {
            "name": "barn",
            "in": "path",
            "required": true,
            "description": "Kennitala einstaklings.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 2
          }
        ],
        "responses": {
          "200": {
            "description": "List of parents.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "404": {
            "description": "No individual exists with that national id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side."
          }
        }
      }
    },
    "/api/v1/einstaklingar/{id}/samibuar": {
      "get": {
        "tags": [
          "Einstaklingar"
        ],
        "summary": "Get the list of residents that live with the individual.",
        "operationId": "Einstaklingar_GetSamibuar",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "National id of the individual.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "List of residents.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "404": {
            "description": "No individual exists with that national id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fasteignir/{id}/ibuar": {
      "get": {
        "tags": [
          "Fasteignir"
        ],
        "summary": "Get the list of residents living in the real estate with the specified real estate id.",
        "operationId": "Fasteignir_GetIbuar",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "Id of the real estate",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "List of residents.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "404": {
            "description": "No real estate exists with that id",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/lyklar": {
      "get": {
        "tags": [
          "Lyklar"
        ],
        "summary": "Get all available gender and cohabition codes.",
        "operationId": "Lyklar_GetLyklar",
        "parameters": [
          {
            "name": "tungumal",
            "in": "query",
            "description": "Text language. Not required. Defaults to IS(Icelandic). EN for english.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "List of available gender and cohabition codes.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Lyklar"
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/lyklar/hjuskaparkodar/{id}/{kyn}": {
      "get": {
        "tags": [
          "Lyklar"
        ],
        "summary": "Get details of cohabition code by id.",
        "operationId": "Lyklar_GetHjuskapar",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "Id of cohibition.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          },
          {
            "name": "kyn",
            "in": "path",
            "required": true,
            "description": "Gender code.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 2
          },
          {
            "name": "tungumal",
            "in": "query",
            "description": "Text language. Not required. Defaults to IS(Icelandic). EN for english.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 3
          }
        ],
        "responses": {
          "200": {
            "description": "Details for the cohabition code.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Kodar"
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "404": {
            "description": "No cohibition code exists with that id or gender code.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/lyklar/kyn/{id}": {
      "get": {
        "tags": [
          "Lyklar"
        ],
        "summary": "Get details for gender code by id.",
        "operationId": "Lyklar_GetKyn",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "Id of gender.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          },
          {
            "name": "tungumal",
            "in": "query",
            "description": "Text language. Not required. Defaults to IS(Icelandic). EN for english.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 2
          }
        ],
        "responses": {
          "200": {
            "description": "Details for the gender code.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Kodar"
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "404": {
            "description": "No gender code exists with that id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/lyklar/trufelog": {
      "get": {
        "tags": [
          "Lyklar"
        ],
        "summary": "Get all available religion codes.",
        "operationId": "Lyklar_GetTrufelog",
        "responses": {
          "200": {
            "description": "List of all available religion codes.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Kodar"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/lyklar/trufelog/{id}": {
      "get": {
        "tags": [
          "Lyklar"
        ],
        "summary": "Get details for religion code by id.",
        "operationId": "Lyklar_GetTrufelag",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "Id of religion.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "Details for religion code.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Kodar"
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "404": {
            "description": "No religion code exists with that id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/lyklar/sveitarfelog": {
      "get": {
        "tags": [
          "Lyklar"
        ],
        "summary": "Get all available municipality codes.",
        "operationId": "Lyklar_GetSveitarfelog",
        "responses": {
          "200": {
            "description": "List of all available municipality codes.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Kodar"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/lyklar/sveitarfelog/{id}": {
      "get": {
        "tags": [
          "Lyklar"
        ],
        "summary": "Get the details for municipality by id.",
        "operationId": "Lyklar_GetSveitarfelag",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "Id of municipality.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "Details for municipality.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Sveitarfelag"
                }
              }
            }
          },
          "401": {
            "description": "Authorization information is missing or invalid.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "404": {
            "description": "Municipality does not exist.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          },
          "500": {
            "description": "There was an error on the server side.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Einstaklingsupplysingar": {
        "type": "object",
        "example": {
          "kennitala": "3311305959",
          "nafn": "Ólafur pái Höskuldsson",
          "eiginnafn": "Ólafur",
          "millinafn": "pái",
          "kenninafn": "Höskuldsson",
          "fulltnafn": "Ólafur pái Höskuldsson Dala-Kollsson",
          "kynkodi": "1",
          "bannmerking": false,
          "faedingardagur": "2000-01-28T17:09:02.044Z",
          "logheimili": {
            "heiti": "Öskubakki 15",
            "postnumer": 113,
            "stadur": "Reykjavík",
            "sveitarfelagsnumer": "0000"
          },
          "adsetur": {
            "heiti": "Heilsulind 18",
            "postnumer": 213,
            "stadur": "Kópavogur",
            "sveitarfelagsnumer": "1000"
          }
        },
        "additionalProperties": false,
        "properties": {
          "kennitala": {
            "type": "string",
            "nullable": true
          },
          "nafn": {
            "type": "string",
            "nullable": true
          },
          "eiginnafn": {
            "type": "string",
            "nullable": true
          },
          "millinafn": {
            "type": "string",
            "nullable": true
          },
          "kenninafn": {
            "type": "string",
            "nullable": true
          },
          "fulltNafn": {
            "type": "string",
            "nullable": true
          },
          "kynkodi": {
            "type": "string",
            "nullable": true
          },
          "bannmerking": {
            "type": "boolean"
          },
          "faedingardagur": {
            "type": "string",
            "format": "date-time"
          },
          "logheimili": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/Heimilisfang"
              }
            ]
          },
          "adsetur": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/Heimilisfang"
              }
            ]
          }
        }
      },
      "Heimilisfang": {
        "type": "object",
        "example": {
          "heiti": "Heilsulind 18",
          "postnumer": "201",
          "stadur": "Kópavogur",
          "sveitarfelagsnumer": "0000"
        },
        "additionalProperties": false,
        "properties": {
          "heiti": {
            "type": "string",
            "nullable": true
          },
          "postnumer": {
            "type": "string",
            "nullable": true
          },
          "stadur": {
            "type": "string",
            "nullable": true
          },
          "sveitarfelagsnumer": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "Empty": {
        "type": "object",
        "additionalProperties": false
      },
      "Faedingarstadur": {
        "type": "object",
        "example": {
          "sveitarfelagsnumer": "0000",
          "stadur": "Reykjavík",
          "faedingardagur": "33.11.0930"
        },
        "additionalProperties": false,
        "properties": {
          "sveitarfelagsnumer": {
            "type": "string",
            "nullable": true
          },
          "stadur": {
            "type": "string",
            "nullable": true
          },
          "faedingardagur": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "Rikisfang": {
        "type": "object",
        "example": {
          "kodi": "IS",
          "land": "Ísland"
        },
        "additionalProperties": false,
        "properties": {
          "kodi": {
            "type": "string",
            "nullable": true
          },
          "land": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "Trufelagsskraning": {
        "type": "object",
        "example": {
          "trufelagskodi": "1",
          "breytt": "2021-01-28T17:09:02.044Z"
        },
        "additionalProperties": false,
        "properties": {
          "trufelagskodi": {
            "type": "string",
            "nullable": true
          },
          "breytt": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          }
        }
      },
      "Heimili": {
        "type": "object",
        "example": {
          "huskodi": "007007007007",
          "fasteignanumer": "1234567",
          "heimilisfang": "Heilsulind 18",
          "postnumer": "201",
          "stadur": "Kópavogur",
          "sveitarfelagsnumer": "0000",
          "landakodi": "IS",
          "Breytt": ""
        },
        "additionalProperties": false,
        "properties": {
          "huskodi": {
            "type": "string",
            "nullable": true
          },
          "fasteignanumer": {
            "type": "string",
            "nullable": true
          },
          "heimilisfang": {
            "type": "string",
            "nullable": true
          },
          "postnumer": {
            "type": "string",
            "nullable": true
          },
          "stadur": {
            "type": "string",
            "nullable": true
          },
          "sveitarfelagsnumer": {
            "type": "string",
            "nullable": true
          },
          "landakodi": {
            "type": "string",
            "nullable": true
          },
          "breytt": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          }
        }
      },
      "Adsetur": {
        "type": "object",
        "example": {
          "huskodi": "007000700700",
          "heimilisfang": "Heilsulind 18",
          "sveitarfelagsnumer": "1000",
          "postnumer": "213",
          "stadur": "Kópavogur",
          "landakodi": null,
          "breytt": "15.06.1550"
        },
        "additionalProperties": false,
        "properties": {
          "huskodi": {
            "type": "string",
            "nullable": true
          },
          "heimilisfang": {
            "type": "string",
            "nullable": true
          },
          "sveitarfelagsnumer": {
            "type": "string",
            "nullable": true
          },
          "postnumer": {
            "type": "string",
            "nullable": true
          },
          "stadur": {
            "type": "string",
            "nullable": true
          },
          "landakodi": {
            "type": "string",
            "nullable": true
          },
          "breytt": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          }
        }
      },
      "Lograda": {
        "type": "object",
        "example": {
          "erLograda": true
        },
        "additionalProperties": false,
        "properties": {
          "erLograda": {
            "type": "boolean"
          }
        }
      },
      "Hjuskapur": {
        "type": "object",
        "example": {
          "kennitalaMaka": "3310286969",
          "nafnMaka": "Þorgerður Egilsdóttir",
          "hjuskaparkodi": "3",
          "breytt": "30.02.0955"
        },
        "additionalProperties": false,
        "properties": {
          "kennitalaMaka": {
            "type": "string",
            "nullable": true
          },
          "nafnMaka": {
            "type": "string",
            "nullable": true
          },
          "hjuskaparkodi": {
            "type": "string",
            "nullable": true
          },
          "breytt": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "Fjolskylda": {
        "type": "object",
        "example": {
          "fjolskyldunumer": "3311305959",
          "einstaklingar": [
            {
              "nafn": "Ólafur pái Höskuldsson",
              "kennitala": "3311305959"
            },
            {
              "nafn": "Þorgerður Egilsdóttir",
              "kennitala": "3310286969"
            },
            {
              "kennitala": "3311616969",
              "nafn": "Kjartan Ólafsson"
            }
          ]
        },
        "additionalProperties": false,
        "properties": {
          "fjolskyldunumer": {
            "type": "string",
            "nullable": true
          },
          "einstaklingar": {
            "type": "array",
            "nullable": true,
            "items": {
              "$ref": "#/components/schemas/Einstaklingur"
            }
          }
        }
      },
      "Einstaklingur": {
        "type": "object",
        "example": {
          "nafn": "Ólafur pái Höskuldsson",
          "kennitala": "3311305959"
        },
        "additionalProperties": false,
        "properties": {
          "nafn": {
            "type": "string",
            "nullable": true
          },
          "kennitala": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "ProblemDetails": {
        "type": "object",
        "additionalProperties": {
          "nullable": true
        },
        "properties": {
          "type": {
            "type": "string",
            "nullable": true
          },
          "title": {
            "type": "string",
            "nullable": true
          },
          "status": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "detail": {
            "type": "string",
            "nullable": true
          },
          "instance": {
            "type": "string",
            "nullable": true
          },
          "extensions": {
            "type": "object",
            "nullable": true,
            "additionalProperties": {}
          }
        }
      },
      "Lyklar": {
        "type": "object",
        "example": {
          "kyn": {
            "1": {
              "lysing": "Karl"
            },
            "2": {
              "lysing": "Kona"
            }
          },
          "hjuskapur": {
            "0": {
              "1": {
                "lysing": "Íslendingur með lögheimili erlendis; í hjúskap með útlendingi sem ekki er á skrá"
              },
              "2": {
                "lysing": "Íslendingur með lögheimili erlendis; í hjúskap með útlendingi sem ekki er á skrá"
              },
              "7": {
                "lysing": "Íslendingur með lögheimili erlendis; í hjúskap með útlendingi sem ekki er á skrá"
              }
            }
          }
        },
        "additionalProperties": false,
        "properties": {
          "kyn": {
            "type": "object",
            "nullable": true,
            "additionalProperties": {
              "$ref": "#/components/schemas/Skilgreining"
            }
          },
          "hjuskapur": {
            "type": "object",
            "nullable": true,
            "additionalProperties": {
              "type": "object",
              "additionalProperties": {
                "$ref": "#/components/schemas/Skilgreining"
              }
            }
          }
        }
      },
      "Skilgreining": {
        "type": "object",
        "example": {
          "lysing": "Kona"
        },
        "additionalProperties": false,
        "properties": {
          "lysing": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "Kodar": {
        "type": "object",
        "example": {
          "kodi": "1",
          "lysing": "Karl"
        },
        "additionalProperties": false,
        "properties": {
          "kodi": {
            "type": "string",
            "nullable": true
          },
          "lysing": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "Sveitarfelag": {
        "type": "object",
        "example": {
          "nafn": "Reykjavík",
          "nafnThgf": "Reykjavík",
          "postnumer": "101"
        },
        "additionalProperties": false,
        "properties": {
          "nafn": {
            "type": "string",
            "nullable": true
          },
          "nafnThgf": {
            "type": "string",
            "nullable": true
          },
          "postnumer": {
            "type": "string",
            "nullable": true
          }
        }
      }
    },
    "securitySchemes": {
      "Basic": {
        "type": "http",
        "description": "Provide Basic Authentiation",
        "name": "Authorization",
        "in": "header",
        "scheme": "basic"
      }
    }
  },
  "security": [
    {
      "Basic": []
    }
  ]
}